# Generated by Django 3.2.8 on 2021-12-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
